eureka:
  client:
    service-url:
      defaultZone: http://admin:ss981124@localhost:8761/eureka/
      register-with-eureka: true
      fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port} #:${random.long(1,100)}