server:
  port: 10940

spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  profiles:
    active: dev
  application:
    name: service-stream
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${DATABASE_HOST}:3306/brainoverflow?serverTimezone=Australia/Sydney&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: ss981124
  rabbitmq:
    host: 47.74.84.224
    port: 5672
    username: guest
    password: ss981124
  redis:
    host: ${DATABASE_HOST}
    port: 6379
    password: ss981124
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.gogohd.stream.controller

knife4j:
  enable: true
  setting:
    language: en