server:
  port: 10900

spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  profiles:
    active: dev
  application:
    name: service-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-ucenter
          uri: lb://service-ucenter
          predicates:
            - Path=/service-ucenter/**
          filters:
            - StripPrefix=1
        - id: service-edu
          uri: lb://service-edu
          predicates:
              - Path=/service-edu/**
          filters:
              - StripPrefix=1

knife4j:
  gateway:
    enabled: true
    strategy: discover
    discover:
      enabled: true
      version: openapi3
